"""Added users.password

Revision ID: 29004f6c303f
Revises: 383f2a446942
Create Date: 2022-10-18 14:53:52.485026

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "29004f6c303f"
down_revision = "383f2a446942"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###
